name = "so-rawan-website"
main = "worker/worker.js"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

[env.production]
workers_dev = true

[env.production.vars]
SPREADSHEET_ID = "16hi5AoG-CstZ-gDSKLIcJZ_SkcoCn-caVRRMIRA-d5Y"
SERVICE_ACCOUNT_EMAIL = "your-service-account@project.iam.gserviceaccount.com"
NODE_ENV = "production"
