name = 'so-rawan-website'
compatibility_date = '2024-01-15'
compatibility_flags = ['nodejs_compat']
main = 'worker/worker.js'

[env.development]
workers_dev = true

[vars]
NODE_ENV = 'development'

[env.production]
workers_dev = false

[vars]
NODE_ENV = 'production'
