name = 'so-rawan-website'
compatibility_date = '2024-01-15'
compatibility_flags = ['nodejs_compat']
main = 'worker/worker.js'

[env.development]
workers_dev = true

[vars]
SPREADSHEET_ID = 'your-spreadsheet-id-here'
SERVICE_ACCOUNT_EMAIL = 'your-service-account@project.iam.gserviceaccount.com'
